# -*- coding: utf-8 -*-
"""001. exerci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146yVIa9JMZ1G0_luTEYbgxk1Kh-We2Ec

[Lista exercicio - python brazil](https://wiki.python.org.br/ListaDeExercicios)
"""

## 01 - Faça um Programa que mostre a mensagem "Alo mundo" na tela.

print("Hello, World")

## 02 - Faça um Programa que peça um número e então mostre a mensagem O número informado foi [número].

n = input(int)

print(f"o número informado foi: {n}")

## 03 - Faça um Programa que peça dois números e imprima a soma.

x = int(input("Informe um número: "))
y = int(input("Informe outro número: "))

n = x + y

print(f"a soma de {x} + {y} é igual a {n}")

## 04 - Faça um Programa que peça as 4 notas bimestrais e mostre a média.

nota1 = float(input("Infome a nota do Primeiro bimestre: "))
nota2 = float(input("Infome a nota do Segundo bimestre: "))
nota3 = float(input("Infome a nota do Terceiro bimestre: "))
nota4 = float(input("Infome a nota do Quarto bimestre: "))

m = (nota1 + nota2 + nota3 + nota4)/4

print(f"A média de duas nostas é {m}")

## 05 - Faça um Programa que converta metros para centímetros.

m = int(input("Informe o valor em metros: "))

cm = m * 100

print(f"A conversão de m para cm é: {cm}")

''' 06 - Faça um Programa que peça o raio de um círculo, calcule e mostre sua área.'''

r = int(input("informe o raio: "))

h = 3.14 * r **2

print(h)

## or

import math   ### importar a biblioteca math

raio = float(input("Informe o raio do círculo: "))

area = math.pi * raio ** 2

print(f"A área do círculo com raio {raio} é: {area:.2f}")

## 07 - Faça um Programa que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário.

lado = 5

area = lado ** 2
area2 = area * 2

print(f"O dobro da aréa de um quadrado é {area2} ")

## 08 - Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês.
#Calcule e mostre o total do seu salário no referido mês.

valor_horas = float(input("Informe quanto você ganha por hora: "))
horas_trab = float(input("Informe o número de horas trabalhadas no mês: "))

salario = valor_horas * horas_trab

print(f"O total do seu salário em um mês é R${salario}")

## 10 -Faça um Programa que peça a temperatura em graus Fahrenheit, transforme e mostre a temperatura em graus Celsius.
#C = 5 * ((F-32) / 9).

tempF = float(input("Informe a temperatura em Fahrenheit: "))
C = 5 * ((tempF-32) / 9)

print(f"A tempereratura de {tempF} Fahrenheit em Celsius é °{C:.1f} ")

''' 11. Faça um Programa que peça 2 números inteiros e um número real.
  Calcule e mostre:
  a - o produto do dobro do primeiro com metade do segundo .
  b - a soma do triplo do primeiro com o terceiro.
  c - o terceiro elevado ao cubo. '''

# a

numero1 = int(input("Informe um número inteiro: "))
numero2 = int(input("Informe outro número inteiro: "))
numero3 = float(input("Informe um número real: "))

dobro = numero1 * 2
metade_2 = numero2 / 2
produto = dobro * metade_2

print(f"a - O valor do dobro do primeiro com metade do segundo é {produto} ")

# b

triplo = numero1 * 3
soma = triplo + numero3

print(f" b - A soma do triplo do primeiro com o terceiro é {soma}")

# c

cubo = numero3 **3

print(f"c - o terceiro elevado ao cubo é {cubo}")

''' 12. Tendo como dados de entrada a altura de uma pessoa,
construa um algoritmo que calcule seu peso ideal, usando a
seguinte fórmula: (72.7*altura) - 58 '''

altura = float(input("Informe sua altura: "))

peso = (72.7 * altura) - 58

print(f"Seu peso ideal é: {peso}")

''' 13. Tendo como dado de entrada a altura (h) de uma pessoa, construa um algoritmo
 que calcule seu peso ideal, utilizando as seguintes fórmulas:
      Para homens: (72.7*h) - 58
      Para mulheres: (62.1*h) - 44.7 '''

altura = float(input("Informe sua altura: "))
sexo = str(input("Informe seu sexo M (Masculino) F (feminino): "))

if sexo == 'M':
  peso = (72.7 * altura) - 58
else:
  peso = (62.1 * altura) - 44.7

print(f"Seu peso ideal é: {peso:.2f}")

''' 14. João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento
diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento
de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente.
João precisa que você faça um programa que leia a variável peso (peso de peixes) e calcule o excesso.
Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que
João deverá pagar. Imprima os dados do programa com as mensagens adequadas. '''

limite_peso = 50.0
multa_por_kilo = 4.00

peso = float(input("Informe o valor do peso do peixe: "))

if peso > limite_peso:
  excesso = peso - limite_peso
  multa = excesso * multa_por_kilo
  print(f"O pesso excede do limite permitido {excesso:.2f}")
  print(f"você deve pagar uma multa no valor de {multa:.2f}")
else:
  print("Parabéns o peso do peixe é ideal para o estado de São Paulo, você não prescisa pagar a multa")

