# -*- coding: utf-8 -*-
"""002.livro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1521u8Tnm_lWhlQRhMrjKDaOsbUmWlr4Y

exercicio - livro: Python para Todos
Explorando Dados com Python 3
Charles R. Severance
"""

''' Exercício 2: Escreva um programa que use inputs para solicitar ao
usuário seu nome e, em seguida, faça um cumprimento.'''

nome = input("Infome seu nome: ")

print(f"olá {nome}, seja bem vindo(a)")

''' Exercício 3: Escreva um programa que solicite ao usuário as horas e o
valor da taxa por horas para calcular o valor a ser pago por horas de
serviço. '''

hora = float(input("digite as horas: "))
valor = float(input("digite o valor: "))

valor_pago = hora * valor

print(f"O valor a ser pago por hora é: {valor_pago}")

''' Exercício 4: Suponha que executamos as seguintes declaração por
atribuição:
Largura = 17
Altura = 12.0
Para cada uma das expressões a seguir, escreva o valor da expressão e o tipo (do
valor da expressão).
1. Largura//2
2. Largura/2.0
3. Altura/3
4. 1 + 2 * 5 '''

largura = 17
altura = 12.0

print(largura//2)
print(largura/2.0)
print(altura/3)
print(1 + 2 * 5)

''' Exercício 5: Escreva um programa que solicite ao usuário uma temperatura
Celsius, converta para Fahrenheit, e mostre a temperatura
convertida. '''

celsius = float(input("Informe a temperatura em ºC: "))

fahrenheit = (celsius * 9/5) + 32

print(f" a temperatuda de ºC {celsius} em Fahrenheit é: {fahrenheit}")

''' Exercício 1: Reescreva seu programa de pagamento, para pagar ao funcionário
1.5 vezes o valor da taxa horária de pagamento pelo tempo
trabalhado acima de 40 horas '''

hora = float(input("digite as horas: "))
valor = float(input("digite o valor: "))

if hora > 40:
  horas_extras = hora - 40  # descubrir quantas horas extra o funcionario trabalhou
  valor_pago = (40 * valor) + (horas_extras * valor * 1.5)
  print(f"O valor a ser pago por hora é: {valor_pago}")

else:
  valor_pago = hora * valor

  print(f"O valor a ser pago por hora é: {valor_pago}")

''' Exercício 2: Reescreva seu programa de pagamento utilizando try e
except, de forma que o programa consiga lidar com entradas não numéricas
graciosamente, mostrando uma mensagem e saindo do programa. A
seguir é mostrado duas execuções do programa '''

''' Exercício 3: Escreva um programa que peça por uma pontuação entre
0.0 e 1.0. Se a pontuação for fora do intervalo, mostre uma mensagem
de erro. Se a pontuação estiver entre 0.0 e 1.0, mostre a respectiva nota
usando a seguinte tabela

Pontuação Nota
>= 0.9 A
>= 0.8 B
>= 0.7 C
>= 0.6 D
< 0.6 F    '''

pontuacao = float(input("Informe uma poduação entre 0.0 e 1.0: "))

if pontuacao < 0.0 or pontuacao > 1.0:
  print("Erro pontuação invalida")
elif pontuacao >= 0.9:
  print("sua nota foi A")
elif pontuacao >= 0.8:
  print("sua nota foi B")
elif pontuacao >= 0.7:
  print("sua nota foi C")
elif pontuacao >= 0.6:
  print("sua nota foi D")
elif pontuacao < 0.6:
  print("sua nota foi F")

print("Fim do programa, obrigada")

